export default interface Pet {
  active?: boolean;
  age_key?: string;
  application_adopted_date?,
  application_approved_date?,
  bk_breed_primary_id?,
  bk_breed_secondary_id?,
  bk_specie_id?,
  branch_id?: number,
  breed_primary_id?: number,
  breed_secondary_id?,
  canonical?: string,
  created_date?: string,
  creator_user_id?; number;
  custom_code?,
  cycle: number,
  deleted: boolean;
  description?: string,
  error_breed?,
  external_id?,
  first_application_date?,
  gallery_id?: number,
  global_code?: number,
  id?: number,
  import?: boolean,
  integration_sync_id?,
  internal_code?: number,
  mix?,
  modified_date?: string,
  name?: string,
  neutered?,
  petfinder_breed?,
  petfinder_status?,
  petfinder_type?,
  picture?: string,
  price?,
  schema_name?: string,
  sex_key?: string,
  size_key?: string,
  specie_id?: number,
  status_key?: string,
  table_name?: string,
  updater_user_id?: number,
  uuid?: string,
  vaccinated?,
  verify_again?,
  version?: number
}
